name: Bump Version

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Nightly Merge"]
    types: [completed]


jobs:
  version-up:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: 🚛 Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: 🔎 Determine next version type
      id: version_type
      run: |
        git log $(git describe --tags --abbrev=0)..HEAD --merges --oneline > new-in-this-release.log
        TYPE=$(python ./tools/ci_tools.py --logfile new-in-this-release.log)

        echo ::set-output name=type::$TYPE

    - name: ➕ Calculate next version
      id: next_version
      uses: pypeclub/semver-release-action@master
      with:
        prefix: nightly/
        dry_run: true
        bump: ${{ steps.version_type.outputs.type }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: 💉 Inject new version into files
      run: python ./tools/ci_tools.py $VERSION

    - name: 💾 Commit changes
      id: git_commit
      run: |
        git config user.email ${{ secrets.CI_EMAIL }}
        git config user.name ${{ secrets.CI_USER }}
        git add .
        git commit -m "[Automated] Bump version"
        git push
        
        echo ::set-output name=sha::$(git rev-parse HEAD)

    - name: 🔨 Merge main back to develop    
      uses: everlytic/branch-merge@1.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_ref: 'main'
        target_branch: 'develop'
        commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'

    - name: 🚀 Tag and Release
      uses: pypeclub/semver-release-action@master
      with:
        prefix: nightly/
        bump: ${{ steps.next_version.outputs.match }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.git_commit.outputs.sha }}