name: Nightly Merge

on:
  schedule:
    - cron:  '3 21 1-5 * *'
  workflow_dispatch:

jobs:
  Ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - name: 🚛 Checkout Code
      uses: actions/checkout@v2

    - name: Merge development -> main
      uses: tukasz/direct-merge-action@master
      with:
        github_token: ${{ github.token }}
        source-branch: develop
        target-branch: main
        commit-message: [Automated] merge Develop to Main