name: Release Stable

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  find_version:
    runs-on: ubuntu-latest

    steps:
    - name: 🚛 Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.7

    - name: "✏️ Generate changelog"
      if: steps.version_type.outputs.type != 'skip'
      id: generate-last-changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        breakingLabel: '### 💥 Breaking'
        enhancementLabel: '### 🚀 Enhancements'
        bugsLabel: '### 🐛 Bug fixes'
        deprecatedLabel: '### ⚠️ Deprecations'
        addSections: '{"documentation":{"prefix":"### 📖 Documentation","labels":["documentation"]},"tests":{"prefix":"### ✅ Testing","labels":["tests"]}}'
        issues: false
        issuesWoLabels: false
        pullRequests: true
        prWoLabels: false
        author: false
        compareLink: true
        stripGeneratorNotice: true
        verbose: true
        excludeTagsRegex: "nightly/.+"
        futureRelease: ${{ github.ref }}
        releaseBranch: "main"
        onlyLastTag: true
        stripHeaders: true

    - name: "🖨️ Print changelog to console"
      run: echo ${{ steps.generate-last-changelog.outputs.changelog }}

    - name: "Release"
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        body: ${{ steps.generate-last-changelog.outputs.changelog }}

    # - name: 💾 Commit changes
    #   id: git_commit
    #   if: steps.version_type.outputs.type != 'skip'
    #   run: |
    #     git config user.email ${{ secrets.CI_EMAIL }}
    #     git config user.name ${{ secrets.CI_USER }}
    #     git add .
    #     git commit -m "[Automated] Bump version"
    #     git push
        
    #     echo ::set-output name=sha::$(git rev-parse HEAD)

    # - name: 🔨 Merge main back to develop    
    #   uses: everlytic/branch-merge@1.1.0
    #   if: steps.version_type.outputs.type != 'skip'
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     source_ref: 'main'
    #     target_branch: 'develop'
    #     commit_message_template: '[Automated] Merged {source_ref} into {target_branch}'

    # - name: 🚀 Tag and Release
    #   uses: pypeclub/semver-release-action@master
    #   if: steps.version_type.outputs.type != 'skip'
    #   with:
    #     prefix: nightly/
    #     bump: ${{ steps.next_version.outputs.match }}
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     sha: ${{ steps.git_commit.outputs.sha }}