name: Release Stable

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  find_version:
    runs-on: ubuntu-latest

    steps:
    - name: 🚛 Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.7

    - name: Get latest stable tag
      id: last_version
      run: |
        since_tag=`git tag --list 'v[0-9]*' | sort -V | tail -2 | head -1`
        due_tag=`git tag --list 'v[0-9]*' | sort -V | tail -1`
        echo $since_tag
        echo $due_tag
        ::set-output name=since_tag::$since_tag
        ::set-output name=due_tag::$due_tag


    - name: "✏️ Generate changelog"
      if: steps.version_type.outputs.type != 'skip'
      id: generate-last-changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        breakingLabel: '### 💥 Breaking'
        enhancementLabel: '### 🚀 Enhancements'
        bugsLabel: '### 🐛 Bug fixes'
        deprecatedLabel: '### ⚠️ Deprecations'
        addSections: '{"documentation":{"prefix":"### 📖 Documentation","labels":["documentation"]},"tests":{"prefix":"### ✅ Testing","labels":["tests"]}}'
        issues: false
        issuesWoLabels: false
        pullRequests: true
        prWoLabels: false
        author: false
        compareLink: true
        stripGeneratorNotice: true
        verbose: true
        excludeTagsRegex: "nightly/.+"
        releaseBranch: "main"
        sinceTag: "${{ steps.last_version.outputs.since_tag }}"
        dueTag: "${{ steps.last_version.outputs.due_tag }}"
        stripHeaders: true

    - name: "🖨️ Print changelog to console"
      run: echo ${{ steps.generate-last-changelog.outputs.changelog }}

    - name: "Release"
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        body: ${{ steps.generate-last-changelog.outputs.changelog }}