name: Release Stable

on:
  push:
    tags:
      - '*[0-9].*[0-9].*[0-9]*'

jobs:
  find_version:
    runs-on: ubuntu-latest

    steps:
    - name: 🚛 Checkout Code
      uses: actions/checkout@v2

    - name: "✏️ Generate changelog"
      if: steps.version_type.outputs.type != 'skip'
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "false"
        ALLOW_TAG_PREFIX: "true"

    - name: "Release"
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        body: ${{ steps.generate-last-changelog.outputs.changelog }}