name: version_up

on:
  push:
    branches: [main]


jobs:
  Ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - name: 🚛 Checkout Code
      uses: actions/checkout@v2

    - id: next_version
      uses: zwaldowski/semver-release-action@v2
      with:
        dry_run: true
        bump: minor
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # Do something to modify the repo using `${{ steps.next_version.outputs.version }}`.
    - run: echo "${{ steps.next_version.outputs.version }}"
    - run: |
        git config user.email ${{ secrets.CI_EMAIL }}
        git config user.name ${{ secrets.CI_USER }}
        git add .
        git commit -m "Bump version"
        git push
        
        echo ::set-output name=sha::$(git rev-parse HEAD)
    - uses: zwaldowski/semver-release-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.git_commit.outputs.sha }}